name: stocker
description: Stocker is a software to manage chemical products of National University


publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons


  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Bold.ttf
          - asset: assets/fonts-Regular.ttf

