name: Stocker Deploy

# Controls when the action will run.
  on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
      branches: [develop]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@master
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: "stable"
        - name: Clean
          run: flutter clean
        - name: Install Dependencies
          run: flutter pub get
        - name: Generator
          run: flutter pub run build_runner build --delete-conflicting-outputs
        - name: Build
          run: flutter build web
        - name: Deploy
          uses:
            netlify/deploy@v2
          with:
            publish: build/web
            auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            site_id: ${{ secrets.NETLIFY_SITE_ID }}
            production: true
            functions: functions
            publish_dir: build/web